# Generated by Django 5.1.7 on 2025-03-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_female_car_date_car_time_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='time',
        ),
    ]
