# Generated by Django 5.1.7 on 2025-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('instructor', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
