# Generated by Django 5.1.7 on 2025-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('grade', models.FloatField()),
                ('courses', models.ManyToManyField(to='courses.course')),
            ],
        ),
    ]
